In [38]:
# Experiment 9 - Study of Numpy Library
# Name: Rachit Jajoo
# PRN: 25070123088
# Batch: ENTC - B1

In [39]:
# Why is Numpy used?
# Numpy is faster than lists.
# Numpy is used for numerical computation.
# Numpy is the base for pandas.

In [40]:
# Code 1: Declaration of Numpy

import numpy as np

a = np.array([1,10,20,30,40,50,100])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)

[  1  10  20  30  40  50 100]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
# Code 2: Dimension of Array
print(a.ndim)
print(b.ndim)

1
2


In [42]:
# Code 3: Size of Array
print(a.size)
print(b.size)

7
9


In [43]:
# Code 4: Shape of Array
print(a.shape)
print(b.shape)

(7,)
(3, 3)


In [44]:
# Code 5: Datatype of Array
print(a.dtype)
print(b.dtype)

int64
int64


In [45]:
# Test for another command: display

import numpy as np

a = np.array([1,10,20,30,40,50,100])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
display(a)
display(b)

array([  1,  10,  20,  30,  40,  50, 100])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# DIY 1: Learning aboutn in-built functions using Numpy
# Note: The default datatype is a float.
# If you dont want the period or a float then you have to typecast it into an integer or some other type.

# np.zeros will print 0 in the defined number of rows and columns.
print(np.zeros((2,3)))
print()

# np.ones will print 1 in the defined number of rows and columns.
print(np.ones((3,3)))
print()

# np.eye will print a diagonal matrix in the defined number.
print(np.eye(3))
print()

# np.arange will print the values in ascending order based on the limits and spacing.
print(np.arange(1,10,2))
print()

# np.linspace() generates evenly spaced numbers between a specified start and end value (including both endpoints) in a given number of steps.
print(np.linspace(0,1,4))
print()
# linspace formula is: Step Size = (stop - start) / (num - 1)

print(b * 2)
print()
# print(c) - consider it a new matrix c
print(a + 5)
print()
# print(d) - cibsuder it a new matrix d

# np.mean command prints the mean values of the matrix defined.
print(np.mean)
print()
print(np.mean(a))
print()
print(np.mean(b))
print()

# np.median command prints the median values of the matrix defined.
print(np.median(a))
print()
print(np.median(b))
print()

# np.max and np.min command prints the maximum and the minimum value of the matrix.
print(np.max(a))
print()
print(np.min(a))
print()

# `print(np.sum(a))` → Prints the sum of all elements in array `a`.
print(np.sum(a))
print()



# print(np.std(a)) → Prints the standard deviation of elements in array `a`.
print(np.std(a))
print()

# print(np.var(a)) → Prints the variance of elements in array `a`.
print(np.var(a))
print()

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[1 3 5 7 9]

[0.         0.33333333 0.66666667 1.        ]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[  6  15  25  35  45  55 105]

<function mean at 0x79b39b5d5a80>

35.857142857142854

5.0

30.0

5.0

100

1

251

30.474479118616948

928.6938775510205



In [47]:
# DIY 2: Take a matrix and perform all operations on it.
# Note: I was trying to implement this code on my own. It was not discussed in class.
# Numpy can be used in various applications and this is one of them.

import numpy as np

# Define a matrix
A = np.array([[1, 2],
              [3, 4]])

print("Matrix A: ")
print(A)

# Transpose
print("\nTranspose of A: ")
print(A.T)

# Determinant
print("\nDeterminant of A: ")
print(np.linalg.det(A))

# Inverse
print("\nInverse of A: ")
print(np.linalg.inv(A))

# Matrix Multiplication (A × A)
print("\nMultiplication of A with A: ")
print(np.dot(A, A))

Matrix A: 
[[1 2]
 [3 4]]

Transpose of A: 
[[1 3]
 [2 4]]

Determinant of A: 
-2.0000000000000004

Inverse of A: 
[[-2.   1. ]
 [ 1.5 -0.5]]

Multiplication of A with A: 
[[ 7 10]
 [15 22]]
